# Generated by Django 5.2.4 on 2025-08-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_userprofile_options_alter_userprofile_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('furniture', 'Furniture'), ('apparel', 'Apparel'), ('books', 'Books'), ('kitchen', 'Kitchen'), ('gaming', 'Gaming'), ('beauty', 'Beauty'), ('office', 'Office'), ('sports', 'Sports'), ('toys', 'Toys')], max_length=50),
        ),
    ]
