# Generated by Django 5.2.4 on 2025-08-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='department_branch',
            field=models.CharField(blank=True, choices=[('sales', 'Sales'), ('marketing', 'Marketing'), ('hr', 'Human Resources'), ('it', 'IT Department'), ('finance', 'Finance')], max_length=50, null=True),
        ),
    ]
