# Generated by Django 5.2.4 on 2025-08-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_business_business_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-08-16 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('furniture', 'Furniture'), ('apparel', 'Apparel'), ('books', 'Books'), ('kitchen', 'Kitchen'), ('gaming', 'Gaming'), ('beauty', 'Beauty'), ('office', 'Office'), ('sports', 'Sports'), ('toys', 'Toys'), ('groceries', 'Groceries / Food & Beverages'), ('automotive', 'Automotive / Vehicle Accessories'), ('health', 'Health / Personal Care'), ('stationery', 'Stationery / School Supplies'), ('home_decor', 'Home Decor / Garden')], max_length=50),
        ),
    ]
