# Generated by Django 5.2.4 on 2025-08-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_product_price_alter_product_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('business', 'sku')},
        ),
    ]
