# Generated by Django 5.2.4 on 2025-08-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_order_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='return',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='return',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='return',
            name='updated_at',
        ),
    ]
