# Generated by Django 5.2.4 on 2025-08-18 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_order_created_at_remove_order_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='return',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='inventory.business'),
        ),
        migrations.AddField(
            model_name='return',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='inventory.business'),
        ),
        migrations.AddField(
            model_name='return',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='inventory.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='return',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
