# Generated by Django 5.2.4 on 2025-08-18 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='return',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='inventory.order'),
        ),
    ]
