# Generated by Django 5.2.4 on 2025-08-21 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_return_date_alter_return_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesForecastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intercept', models.FloatField()),
                ('polynomial_degree', models.IntegerField(default=2)),
                ('last_trained', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_forecast_model', to='inventory.business')),
            ],
        ),
    ]
