# Generated by Django 5.2.4 on 2025-08-21 16:46

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_salesforecastmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesforecastmodel',
            name='last_trained',
        ),
        migrations.AddField(
            model_name='salesforecastmodel',
            name='coefficients',
            field=models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='salesforecastmodel',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.business'),
        ),
        migrations.AlterField(
            model_name='salesforecastmodel',
            name='intercept',
            field=models.FloatField(default=0.0),
        ),
    ]
